---
name: pr

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches:
      - trunk
      - release-*
      - feature-*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'trunk' && github.sha || 'any-sha' }}
  cancel-in-progress: true

env:
  IGNORED_PATHS: '(^./docs/|^README.md$|^version.txt$|^acknowledgements.md$)'

jobs:

  # `pr` is a required check for pull requests. Therefore we cannot skip the workflow via 
  # `on.pull_requests.paths-ignore`. Instead, we conditionally run the jobs (which report 
  # a sucess when skipped).
  check_changes:
    runs-on: spiceai-runners
    outputs:
      relevant_changes: ${{ steps.check_changes.outputs.relevant_changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect all code changes
        id: changed-code-files
        uses: dorny/paths-filter@v3
        with:
          filters: |
            code_changes:
              - 'crates/**'
              - 'bin/**'
              - 'test/**'
              - 'install/**'
              - '.github/workflows/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'go.mod'
              - 'go.sum'

      - name: Check for relevant changes
        id: check_changes
        run: |
          echo "relevant_changes=${{ steps.changed-code-files.outputs.code_changes }}" >> $GITHUB_OUTPUT

  lint:
    name: Run Go & Rust Linters
    runs-on: spiceai-runners
    env:
      GOVER: 1.22.0
    needs: check_changes

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        if: needs.check_changes.outputs.relevant_changes == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVER }}
          cache: false

      - name: Install golangci-lint
        if: needs.check_changes.outputs.relevant_changes == 'true'
        run: |
          if ! command -v golangci-lint &> /dev/null ; then
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          fi

      - name: Set up Rust
        uses: ./.github/actions/setup-rust
        if: needs.check_changes.outputs.relevant_changes == 'true'
        with:
          os: 'linux'
      
      - name: Install Protoc
        if: needs.check_changes.outputs.relevant_changes == 'true'
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up make
        uses: ./.github/actions/setup-make

      - name: Set up cc
        uses: ./.github/actions/setup-cc

      - run: make lint
        if: needs.check_changes.outputs.relevant_changes == 'true'

      - name: Check if Cargo.lock is updated
        if: needs.check_changes.outputs.relevant_changes == 'true'
        run: |
          if git diff --exit-code Cargo.lock; then
            echo "Cargo.lock is up to date"
          else
            echo "Update Cargo.lock"
            exit 1
          fi

  build:
    name: Build Go & Rust
    runs-on: spiceai-runners
    env:
      GOVER: 1.22.0
    needs: check_changes

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVER }}
          cache: false

      - name: Set up Rust
        uses: ./.github/actions/setup-rust
        with:
          os: 'linux'

      - name: Set up make
        uses: ./.github/actions/setup-make

      - name: Set up cc
        uses: ./.github/actions/setup-cc

      - run: make ci test
        if: needs.check_changes.outputs.relevant_changes == 'true'

  build-docker:
    name: Build Docker Image
    runs-on: spiceai-runners
    needs: check_changes

    steps:
      - uses: actions/checkout@v4

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        if: needs.check_changes.outputs.relevant_changes == 'true'
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          build-args: |
            CARGO_FEATURES=odbc
          tags: |
            ghcr.io/spiceai/spiceai-rust:ci
